// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDay52GfrXsmmveHF6Y9LMxAq-_uFsFDOo',
    appId: '1:137450961167:web:1fe96cdeb1ce2cd413267a',
    messagingSenderId: '137450961167',
    projectId: 'myfire-collect',
    authDomain: 'myfire-collect.firebaseapp.com',
    storageBucket: 'myfire-collect.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvPV671PoGM_1Iqtzlljbcj8rL-AvFO4A',
    appId: '1:137450961167:android:775a761e8ce2dc2f13267a',
    messagingSenderId: '137450961167',
    projectId: 'myfire-collect',
    storageBucket: 'myfire-collect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqQOrRD7saanPrrKajmJOhVXfVKZBkBtk',
    appId: '1:137450961167:ios:2b839cf01345461a13267a',
    messagingSenderId: '137450961167',
    projectId: 'myfire-collect',
    storageBucket: 'myfire-collect.appspot.com',
    iosClientId: '137450961167-sqovl8uefaihc4q0sd42fnbsvldd4j20.apps.googleusercontent.com',
    iosBundleId: 'com.example.mydataExp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqQOrRD7saanPrrKajmJOhVXfVKZBkBtk',
    appId: '1:137450961167:ios:2b839cf01345461a13267a',
    messagingSenderId: '137450961167',
    projectId: 'myfire-collect',
    storageBucket: 'myfire-collect.appspot.com',
    iosClientId: '137450961167-sqovl8uefaihc4q0sd42fnbsvldd4j20.apps.googleusercontent.com',
    iosBundleId: 'com.example.mydataExp1',
  );
}
